export const EVENT_DATA_CHANGED = 'EVENT_DATA_CHANGED';
export const EVENT_CREATE_ITEM = 'EVENT_CREATE_ITEM';
export const EVENT_RENAME_ITEM = 'EVENT_RENAME_ITEM';
export const EVENT_DELETE_ITEM = 'EVENT_DELETE_ITEM';
export const EVENT_OPEN_FOLDER = 'EVENT_OPEN_FOLDER';
export const EVENT_FILTERS_CHANGED = 'EVENT_FILTERS_CHANGED';
export const EVENT_BREADCRUMB_CHANGED = 'EVENT_BREADCRUMB_CHANGED';
export const EVENT_BREADCRUMB_BACK = 'EVENT_BREADCRUMB_BACK';